name: Deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Ruby and install dependencies
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    - name: Setup deploy options
      id: setup
      env:
        SOURCE_BRANCH: ${{ github.head_ref || github.ref_name }}
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        echo "SRC_BRANCH=$SOURCE_BRANCH" >> "$GITHUB_OUTPUT"
        if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
          echo "NO_PUSH=--no-push" >> "$GITHUB_OUTPUT"
        fi
    - name: Build and deploy website
      env:
        SOURCE_BRANCH: ${{ steps.setup.outputs.SRC_BRANCH }}
        NO_PUSH: ${{ steps.setup.outputs.NO_PUSH }}
      run: printf 'y\n' | bin/deploy --verbose ${NO_PUSH} --src "$SOURCE_BRANCH" --deploy gh-pages
